# Generated by Django 3.0.8 on 2020-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='pdf_copy',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
