# Generated by Django 3.0.8 on 2020-07-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0002_collection_pdf_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_copy', models.FileField(blank=True, null=True, upload_to='pdf')),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='pdf_copy',
        ),
    ]
