# Generated by Django 2.2.8 on 2020-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0003_auto_20200717_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
